FIX ISSUE-140 by using response for returning value
salemdar/ngx-cookie pull request #144
Opened 2020-08-27 08:49 UTC by SuperheroicCoding

@see https://github.com/salemdar/ngx-cookie/issues/140

Using response header set cookie to return cookie value on Server

2020-08-31 08:21 UTC, SuperheroicCoding commented
@salemdar What's the current state? I don't know how to fix the e2e tests. It's a CI problem I think.

2020-08-31 08:22 UTC, salemdar requested changes
Thanks for the good work. I made some comments. It would be very cool if you can check them.

You also need to merge with master to make e2e tests running.

2020-08-31 08:22 UTC, salemdar commented on projects/ngx-cookie-backend/src/lib/cookie-backend-writer.service.ts
>    readAllAsString(): string {
Could you remove blank lines in methods?

2020-08-31 08:22 UTC, salemdar commented on projects/ngx-cookie-backend/src/lib/cookie-backend-writer.service.ts
> +    const responseCookies: string[] | string = (this.response.getHeader('Set-Cookie') as any) ?? '';
Can't we avoid `any` here?

2020-08-31 08:22 UTC, salemdar commented on projects/ngx-cookie-backend/src/lib/cookie-backend-writer.service.ts
> +      sameSite: options?.sameSite,
Unnecessary comma.

2020-08-31 08:22 UTC, salemdar commented on projects/ngx-cookie-backend/src/lib/cookie-backend-writer.service.ts
> +  constructor(
Let's stick to previous indentation.

2020-08-31 08:22 UTC, salemdar commented on projects/ngx-cookie-backend/src/lib/cookie-backend-writer.service.ts
> +      responseCookies instanceof Array
I like utility methods where possible: `Array.isArray(responseCookies)`

2020-08-31 08:22 UTC, salemdar commented on projects/backend-test-app/src/app/app.component.ts
> +    if (isPlatformServer(this.platformId)) {
Good idea 👍

2020-09-07 17:36 UTC, salemdar commented
Hey @SuperheroicCoding ,
Did you have any chance to check my comments?

2020-09-10 14:25 UTC, SuperheroicCoding commented
Hi, just saw your comments. Feel free to adapt it yourself. Because I am currently quite busy. Earliest next week I can work again on it.

2020-09-24 15:01 UTC, SuperheroicCoding commented on projects/ngx-cookie-backend/src/lib/cookie-backend-writer.service.ts
> +      sameSite: options?.sameSite,
removed

2020-09-24 15:01 UTC, SuperheroicCoding commented on projects/ngx-cookie-backend/src/lib/cookie-backend-writer.service.ts
> +  constructor(
fixed

2020-09-24 15:03 UTC, SuperheroicCoding commented
@salemdar Finally found time to include your changes. Please have a look again.

2020-09-30 18:21 UTC, SuperheroicCoding commented
@salemdar Can  you please check again? 
Can you give me hint for fixing the failing e2e tests?

2020-10-21 15:29 UTC, salemdar approved these changes

2020-10-21 15:29 UTC, merged